"""
Django settings for awscognito project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g$c8a#x4-b1wwg=o16vex_v*c&0l*&iwec^av)hr9&3yp)m$i#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'backend',
    'frontend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'awscognito.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/home/delhivery/delhivery_code/aws_cogito/awscognito/templates',
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'awscognito.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
LOCAL_STATICFILES_DIRS = (
    #os.path.join(BASE_DIR, "static"),
    "/home/delhivery/delhivery_code/aws_cogito/awscognito/staticfiles",
)
STATICFILES_DIRS = LOCAL_STATICFILES_DIRS
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

#AWS COGNITO CREDENTIALS
IDENTITYPOOLID = 'ap-northeast-1:3a74e929-d4fa-4c7a-8b3c-840c618bf95b'
ACCOUNTID = '164807658618'
AWS_ACCESS_KEY = 'AKIAIWGERSFOFVAZIXOQ'
AWS_SECRET_KEY = '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'
DEFAULT_REGION_NAME = 'ap-northeast-1'
DEFAULT_USER_POOL_ID = 'ap-northeast-1_urRQE86JV'
DEFAULT_USER_POOL_APP_ID = '3ej7g5qejqsgmpgbt9ojo9amo7' #APP should not have any secret in AWS
DEFAULT_CONFIG = {'region_name':DEFAULT_REGION_NAME,
                  'aws_access_key_id':AWS_ACCESS_KEY,
                  'aws_secret_access_key':AWS_SECRET_KEY}
DEFAULT_USER_POOL_LOGIN_PROVIDER = 'cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_urRQE86JV'










